### ISSUE TITLE
pgfplots Package

### ISSUE THREAD

**Issue by bald6354** [MCG-NKU/CVPR_Template#8] opened 2020-10-23 12:50 UTC
When you add pgfplots package to your preamble it throws an error

Adding...
\usepackage{pgfplots}

Generates error...
 /usr/local/texlive/2020/texmf-dist/tex/latex/ms/everyshi.sty, line 77
LaTeX Error: Command \@EveryShipout@Hook already defined.

**Comment by ltriess** [comment] 2020-11-02 17:25
This happens with several packages. For a hacky solution take a look at #3.
Duplicate of #3 #5

**Closed as completed** 2021-02-05 08:21 UTC
